### ISSUE TITLE
Player can't move

### ISSUE THREAD

**Issue by serega6531** [GeyserMC/MCProtocolLib#133]
Hi, I have the same problem that #32 had. I'm using this code: http://pastebin.com/LBWCQ8ur
But when player joins nothing happens, it just stands still.
Unfortunately, those pastebin pages from @best241 in #32 are expired so I cant see the fixes. How can I fix it?

**Comment by minecraftkeba** [comment]
First: Register ClientPlayerPositionRotationPacket after connecting with this code:

client.getSession().getPacketProtocol().registerOutgoing(200, ClientPlayerPositionRotationPacket.class);

Second: Send ClientPlayerPositionRotationPacket:

client.getSession().send(new ClientPlayerPositionRotationPacket(true, x, y, z, yaw, pitch));

**Comment by serega6531** [comment]
@minecraftkeba, I will try it, thanks

**Comment by serega6531** [comment]
Ok, i tried and i got this

> TestBot lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 200

Which id should I use?

**Comment by serega6531** [comment]
It works with 6 (0x06), but still no movement

**Comment by minecraftkeba** [comment]
No Idea worked for me with id 200

**Comment by serega6531** [comment]
http://wiki.vg/Protocol#Player_Position_And_Look_2
It says that id of Player Position And Look is 0x06.
Even so, my bot doesn't move.
http://pastebin.com/h6nH0etC

**Comment by minecraftkeba** [comment]
Don´t know what the error means.

**Comment by MrPowerGamerBR** [comment]
I know this issue is old, but, @serega6531 , did you find a solution for your problem?

I'm trying to send the packet, however the client doesn't move at all.

```
ClientPlayerPositionRotationPacket cpprp = new ClientPlayerPositionRotationPacket(true, e.getTo().getX(), e.getTo().getY(), e.getTo().getZ(), (float) e.getTo().getYaw(), (float) e.getTo().getPitch());

        client.getSession().send(cpprp);

        ClientPlayerPositionPacket cppp = new ClientPlayerPositionPacket(true, e.getTo().getX(), e.getTo().getY(), e.getTo().getZ());

        client.getSession().send(cppp);
```

(I tried using those two packets, however the client doesn't move, at all)

**Comment by serega6531** [comment]
No, I didn't

**Comment by MrPowerGamerBR** [comment]
@serega6531 :disappointed: 

I know this isn't the place for asking help, but... @Steveice10 could you provide a example on moving the client with MCProtocolLib? I tried every combination possible, however the client doesn't move.

**Comment by MrPowerGamerBR** [comment]
I found the problem:

ServerJoinGamePacket ISN'T returning the correct coordinate where the client is spawning in the server, if you tried to send a Move Packet, it wouldn't do anything, because the coordinates you are recieving in ServerJoinGamePacket are totally different than the coordinates where the client is on the server.

After I done a quick test, I tried changing the X, Y, Z values manually (so I could insert the client coordinates in the server) and, guess what? The client moved without any issues.

Here's my code, if anyone wants to take a quick look:
`package com.mrpowergamerbr.dreamproxy.client;

import java.lang.reflect.Field;
import java.net.Proxy;
import java.util.Arrays;

import org.spacehq.mc.protocol.MinecraftProtocol;
import org.spacehq.mc.protocol.data.message.Message;
import org.spacehq.mc.protocol.data.message.TranslationMessage;
import org.spacehq.mc.protocol.packet.ingame.client.ClientChatPacket;
import org.spacehq.mc.protocol.packet.ingame.client.player.ClientPlayerPositionPacket;
import org.spacehq.mc.protocol.packet.ingame.server.ServerChatPacket;
import org.spacehq.mc.protocol.packet.ingame.server.ServerJoinGamePacket;
import org.spacehq.mc.protocol.packet.ingame.server.world.ServerSpawnPositionPacket;
import org.spacehq.packetlib.Client;
import org.spacehq.packetlib.event.session.DisconnectedEvent;
import org.spacehq.packetlib.event.session.PacketReceivedEvent;
import org.spacehq.packetlib.event.session.SessionAdapter;
import org.spacehq.packetlib.tcp.TcpSessionFactory;

import com.mrpowergamerbr.dreamproxy.DreamProxy;
import com.mrpowergamerbr.dreamproxy.client.packets.ChatPacket;
import com.mrpowergamerbr.dreamproxy.client.packets.DisconnectPacket;
import com.mrpowergamerbr.dreamproxy.client.packets.EntityEquipmentPacket;
import com.mrpowergamerbr.dreamproxy.client.packets.JoinPacket;
import com.mrpowergamerbr.dreamproxy.client.packets.MobEffectPacket;
import com.mrpowergamerbr.dreamproxy.client.packets.PlayerMovePacket;
import com.mrpowergamerbr.dreamproxy.client.packets.SetTimePacket;

import cn.nukkit.Player;

public class DummyClient {
    public Client client;
    String mcpeName = "nameFallback";
    DreamProxy dp;
    public int entityId = 0;
    public double x = 0;
    public double y = 0;
    public double z = 0;

```
public DummyClient(DreamProxy dp) {
    this.dp = dp;

    /*
     * TODO:
     * String name = player;
     */
    mcpeName = "Dummy";
    mcpeName = mcpeName + "_MCPE";

    init();
}

public void init() {
    System.out.println("Initializing Connection for " + mcpeName + "...");

    MinecraftProtocol protocol = new MinecraftProtocol(mcpeName);

    client = new Client("127.0.0.1", 25565, protocol, new TcpSessionFactory(Proxy.NO_PROXY));

    client.getSession().addListener(new SessionAdapter() {
        @Override
        public void packetReceived(PacketReceivedEvent event) {
            if(event.getPacket() instanceof ServerSpawnPositionPacket){
                System.out.println("Recieved ServerSpawnPositionPacket...");

                ServerSpawnPositionPacket sspp = event.<ServerSpawnPositionPacket>getPacket();

                x = sspp.getPosition().getX();
                y = sspp.getPosition().getY();
                z = sspp.getPosition().getZ();

                moveDummy();
            }
            if(event.getPacket() instanceof ServerJoinGamePacket) {
                event.getSession().send(new ClientChatPacket("Hello, this is a test of MCProtocolLib."));
            } else if(event.getPacket() instanceof ServerChatPacket) {
                Message message = event.<ServerChatPacket>getPacket().getMessage();
                System.out.println("Received Message: " + message.getFullText());
                if(message instanceof TranslationMessage) {
                    System.out.println("Received Translation Components: " + Arrays.toString(((TranslationMessage) message).getTranslationParams()));
                }
            }
        }

        @Override
        public void disconnected(DisconnectedEvent event) {
            System.out.println("Disconnected: " + Message.fromString(event.getReason()).getFullText());
            if(event.getCause() != null) {
                event.getCause().printStackTrace();
            }
        }
    });

    client.getSession().connect();
}

protected void moveDummy() {
    Thread t;
    t = new Thread(new Runnable() {

        public void run() {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
            x = x + 0.215;
            client.getSession().send(new ClientPlayerPositionPacket(true, x, y, z));

            System.out.println("DummyClient should be at " + x + ", " + y + ", " + z);
            moveDummy();
        }
    });

    t.start();
}

public void bye() {
    client.getSession().disconnect("Bye Bye! :3");
}
```

}
`

However, sometimes I can't move the client at all, but hey, at least I got the client to move!

**Comment by MrPowerGamerBR** [comment]
If, sometimes, the client doesn't move even after you changed the coords manually, try setting the coords in front of the player.

![http://i.imgur.com/OTlW7GN.gif](http://i.imgur.com/OTlW7GN.gif)

**Comment by MALW3R3** [comment]
@MrPowerGamerBR 
Hi, can you help me with movement ? bcs i have error with your code ;/

And my bots won't move

**Comment by abhithedev200** [comment]
same issue client is not moving
