### ISSUE TITLE
Take Item from Chest

### ISSUE THREAD

**Issue by minecraftkeba** [GeyserMC/MCProtocolLib#170]
I am able to move an Item from the Inventory into the Chest with:

Main.session.send(new ClientWindowActionPacket(MainBot.windowID, 540, MainBot.slot, null, WindowAction.SHIFT_CLICK_ITEM, ShiftClickItemParam.LEFT_CLICK));

But I can not move it back into the Inventory.

How can I do that?

**Comment by JamMasterz** [comment]
Sorry for off topic, but how did you open a chest? Ive been trying for days, and nobody but you knows how :D. Maybe if i know that i will figure out an answer to your question.

**Comment by minecraftkeba** [comment]
If you remaind me tommorow around 5 o´clock, then I will send you an
answer, cause I have the code only one my home pc not on my mobile computer.
So just remaind me tommorow :)

See you soon

**Comment by JamMasterz** [comment]
Well, i don't know what timezone you are in so this is my reminder. I will remove it later to avoid off- topic comments.

**Comment by minecraftkeba** [comment]
Position pos = new Position(x, y, z);
Main.session.send(new ClientPlayerPlaceBlockPacket(pos, Face.TOP, MainBot.inv.get(0), (float) x, (float) y , (float) z));

**Comment by JamMasterz** [comment]
I just got it working. I don't know why it didn't work for you. Basically, when you open a chest, you receive a ServerOpenWindowPacket saying the number of slots the inventory has (27 for normal and 54 for double). Following that, you receive a ServerWindowItemsPacket, which contains an array of the items inside the chest, your inventory and your hotbar, all in one. This means that if you want an item from a double chest, you specify the slot 0 in your code(the chest comes first in the array). If you want to move an item from the last slot of your hotbar to the chest, the slot is 89(54 + 27 + 9 - 1, because the hotbar comes 3rd in the array). If you want to move back the item you took, you gotta first find the slot for it in the array of ItemStack that you got in ServerWindowItemsPacket. Also, you should get ServerWindowItemsPacket after every transaction.
