### ISSUE TITLE
Help with packets

### ISSUE THREAD

**Issue by Mepth** [GeyserMC/MCProtocolLib#221]
Hello, how do I get the number of packages sent the player to int, please help, thanks in advance

:)

**Comment by Mepth** [comment]
And how to support all versions and protocols?

for example 1.7, 1.8, 1.9, 1.10, 1.11

**Comment by Steveice10** [comment]
You could probably set up your packet listener to increment a counter of packets received. As for supporting multiple protocols, that's up to you. You could use some sort of tool to put each library version in a different package, but I don't plan to officially support multiple versions in the library otherwise.

**Comment by Mepth** [comment]
Ok, can you give me packet listener explame?

**Comment by Steveice10** [comment]
Check the example included in the source repository.
