### ISSUE TITLE
example server

### ISSUE THREAD

**Issue by yooniks** [GeyserMC/MCProtocolLib#262]
hi,

Can someone give me a full class with a code to join the server?
I use this: https://pastebin.com/rP2ZkPH1
And it does not work, I have all the time on the screen when attaching to the server the text "Downloading the terrain .."

**Comment by Mareckoo01** [comment]
You can find information [here](http://wiki.vg/Main_Page) and read [this](http://wiki.vg/Protocol)
Minecraft shows you "Downloading the terrain.." because you didn't finish the [login sequence](http://wiki.vg/Protocol_FAQ#What.27s_the_normal_login_sequence_for_a_client.3F)
steps 1. to 9. are done by library i think...
