### ISSUE TITLE
MCAuthLib searching

### ISSUE THREAD

**Issue by HP888** [GeyserMC/MCProtocolLib#281]
Where can i search a MCAuthLib source for this https://github.com/Steveice10/MCProtocolLib/tree/5546770d4b484ce0cad90cdb285ff263b2ac191c MCProtocolLib?

**Comment by Mareckoo01** [comment]
If you are looking for 1.8 compiled jar, you can check my [MCProtocolLib repo](https://github.com/Mareckoo01/MCProtocolLib)..
And for MCAuthLib you can check dependencies in pom.xml in the branch you want...
Otherwise look in [MCAuthLib commit history](https://github.com/Steveice10/MCAuthLib/commits/master)..
(i had few problems while looking for different versions and compiling them so i would recommend looking in my MCPL repo)

**Comment by m3ku** [comment]
@HP888 A niby taki kozak i ma autorskie proxy XDD

**Comment by HP888** [comment]
Śmieszny jesteś typie, może nie chce mi się szukać to co potrzebuje do mcprotocollib ty się najwięcej znasz na tym wielki znawco co się pytał czemu mu eelboty nie działaja ;]] Po za tym właśnie pytam się po to, aby napisać to proxy ;] nikt nie mówił, że juz je mam ;

**Comment by HP888** [comment]
@Mareckoo01 thank you for answering i check this.
