### ISSUE TITLE
Client receiving 0x0B with too high Y-value.

### ISSUE THREAD

**Issue by JeromSar** [GeyserMC/MCProtocolLib#347]
Hi, I'm writing a client. In certain scenarios (can't tell exactly why), I receive a `ServerBlockChangePacket` packet with a really high Y-coordinate (3835 in one instance). Do you have any idea why this might be happening?

**Comment by kamcio96** [comment]
It could be plugin issue. Craftbukkit dosen't check Player:sendBlockChange. Do you have plugins?

**Comment by JeromSar** [comment]
@kamcio96 No plugins on this server. It's running Spigot 1.11.2 with minor unrelated modifications.

**Comment by 0-x-2-2** [comment]
I recommend you look at the vanilla code and see how it handles it

**Comment by Steveice10** [comment]
Older versions aren't supported.

**Comment by JeromSar** [comment]
@Steveice10 Do you think the handling of this packet has changed from 1.11.2 to 1.12 then?

**Comment by Steveice10** [comment]
I don't know, but I also have no way of knowing if the cause was fixed in a newer library version or if it's related to running custom server software.

**Comment by DaMatrix** [comment]
I'm able to reliably reproduce this on a 1.12.2 spigot server by walking along breaking a line of wheat as I go. I think it's caused by [this method in NetUtil](https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/util/NetUtil.java#L89-L97) not handling negative numbers correctly (as described on [wiki.vg](https://wiki.vg/index.php?title=Protocol#Position)). If that's the case, this is also going to be a problem in 1.13.2 and 1.14, as the BlockPos decoding hasn't changed since then.

**Comment by Steveice10** [comment]
Note how that wiki.vg page says the method I'm currently using should work fine in Java. As I recall, it's the same as what the vanilla client/server uses.
