### ISSUE TITLE
Is it also possible to walk legit with the bot?

### ISSUE THREAD

**Issue by TeamMioty** [GeyserMC/MCProtocolLib#439]
Is it also possible to walk legit with the bot?

- sorry for my english

**Comment by ghost** [comment]
Hello, if you're talking about a follower bot, as in the bot will attempt to follow behind you indefinitely then yes that's entirely possible. It gets complicated if you want it to be able to follow you on rails, by boat, or if the path behind you gets blocked or requires using doors or redstone contraptions. But this is something you'll need to write into your own bot program as MCProtocolLib is just a library so that you can talk to Minecraft servers, and little more. I've had to implement my own entity pooling system because I couldn't seem to find a native solution. Think of it like this: MCProtocolLib is your legs, _you_ still need to do the walking.

**Comment by TeamMioty** [comment]
No, that's not what I mean. I want the bot to go to a location without teleporting, so it will not be detected on an AntiCheat.

Would it be possible to do something like that?

**Comment by 0-x-2-2** [comment]
Yes its possible but you will need to write the code for that MCProtocolLib is just the protocol implementation.

**Comment by ghost** [comment]
It's definitely possible, but as 0x22 and I say, MCProtocolLib is just the protocol, so anything you want to _do_ you need to code yourself. Judging by this: _"I want the bot to go to a location without teleporting, so it will not be detected on an AntiCheat."_ I assume that you have tried moving your bot to different locations using the protocol, only to find that bot teleports instead of moving naturally. I would suggest looking into minecraft pathfinding, A* is a good algorithm. Something like that would allow a bot to find paths to the destination based on what it knows, or will know about the terrain. But again it will need even more custom coding in order to bypass obstacles, such as having to build up a cliff or dig down, or use redstone contraptions.

**Comment by Steveice10** [comment]
As others have said, it is possible. You'll want to do your movement in increments such that it looks natural to the server.
