### ISSUE TITLE
Get message without color , etc

### ISSUE THREAD

**Issue by RumoEL** [GeyserMC/MCProtocolLib#626]
How to get a string:"Регистрация: /reg <пароль> <повтор пароля>"

if(event.getPacket() instanceof **ServerChatPacket){

ServerChatPacket chatPacket = (ServerChatPacket) eventPacket;
System.err.println("A:" + chatPacket);
}

A:ServerChatPacket(message=TextComponentImpl{content="", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[TextComponentImpl{content="Регистрация: /reg <пароль> <повтор пароля>", style=StyleImpl{color=NamedTextColor{value="#00aaaa"}, obfuscated=false, bold=false, strikethrough=false, underlined=false, italic=false, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}]}, type=SYSTEM, senderUuid=00000000-0000-0000-0000-000000000000)

**Comment by RumoEL** [comment]
lib version 1.16.5-1

**Comment by Steveice10** [comment]
Text components like those in ServerChatPacket will require some manipulation to build a plain-text string. In general, you would need to handle the various different types of components like text, translation, etc in order to properly construct the full message string.

Assuming you're only dealing with plaintext components like those in this message, though, you can do this with a fairly simply approach. Just pull the base message component out of the packet and recurse through it and its children, casting to TextComponent appending the value of calling "contents()" on each component to a StringBuilder.

**Comment by Steveice10** [comment]
Something like this (written off the top of my head so it might not be quite correct):
```java
public String componentToPlainText(Component c) {
    if (!(c instanceof TextComponent)) return c.toString();
    TextComponent tc = (TextComponent) c;

    StringBuilder b = new StringBuilder(tc.content());
    for (Component child : tc.children()) {
        b.append(componentToPlainText(child));
    }

    return b.toString();
}
```

**Comment by RumoEL** [comment]
Thanks it works
