### ISSUE TITLE
Any converter from Component to a single string?

### ISSUE THREAD

**Issue by ItzAmirreza** [GeyserMC/MCProtocolLib#651]
Hello there,

I was wondering if there is any converter for the `Component` object which comes from `ServerChatPacket` to a single understandable string. If no, how can I only get the content from the Component object?

Thank you.

**Comment by Steveice10** [comment]
You will need to implement your own logic for that based on the component type. For example, a basic text component will just have a plaintext message you can use. A a translation component, however, will have both the name of the message type and any formatting parameters. It's up to you to change that message type name into a formatting string and apply the parameters; otherwise MCProtocolLib would have to maintain a list of essentially every translation of every localized message in Minecraft.
